// Generated by BuildPilot from the validated call transcript for Dubai Health.
// Do not hand-edit business data here across rebuilds — update the source
// requirements and regenerate instead. See src/types/site-config.ts (starter
// template) for the full SiteConfig shape (cinematic or plain variant) and
// docs/DEVIN_3D_WEBSITE_SPEC.md for how each field is used.
import type { SiteConfig } from "./types/site-config";

export const siteConfig: SiteConfig = {
  "variant": "cinematic",
  "businessName": "Dubai Health",
  "purpose": "Free professional website for clinics.",
  "targetAudience": "Families in Al Barsha and nearby areas, mostly for general and pediatric visits, plus working professionals for dermatology.",
  "contact": {},
  "palette": {
    "background": "#F4FFCF",
    "surface": "#FFFFFF",
    "text": "#0A2540",
    "muted": "#6B7A8D",
    "accent": "#2C6BED",
    "accentHover": "#1A4EC6"
  },
  "enquirySection": {
    "id": "enquiry",
    "eyebrow": "Get in touch",
    "heading": "Ask a question or book a visit",
    "body": "Tell us how we can help your family. Our team responds promptly during open hours.",
    "submitLabel": "Send enquiry",
    "enquiryTypes": [
      "General enquiry",
      "Book appointment",
      "Insurance & billing",
      "Medical records & results"
    ],
    "disconnectedMessage": "Form submission is not connected yet.",
    "consentLabel": "I understand that Dubai Health may contact me regarding my inquiry."
  },
  "navigation": [
    {
      "label": "Highlights",
      "href": "#products"
    },
    {
      "label": "Enquire",
      "href": "#enquiry"
    }
  ],
  "assets": {
    "collection": "medical",
    "root": "/assets/medical",
    "framesDirectory": "/assets/medical/frames",
    "productsDirectory": "/assets/medical/products"
  },
  "hero": {
    "directory": "/assets/medical/frames",
    "poster": "/assets/medical/frames/ezgif-frame-001.jpg",
    "filePrefix": "ezgif-frame-",
    "fileExtension": "jpg",
    "framePadding": 3,
    "firstFrame": 1,
    "frameCount": 300,
    "width": 1920,
    "height": 1080,
    "scrollHeightVh": 600,
    "maxDevicePixelRatio": 2,
    "maxCachedFrames": 48,
    "loadConcurrency": 6,
    "narrowViewportBreakpoint": 768,
    "focalPoint": {
      "wide": {
        "x": 0.5,
        "y": 0.5
      },
      "narrow": {
        "x": 0.62,
        "y": 0.5
      }
    },
    "chapters": [
      {
        "id": "opening",
        "from": 0,
        "to": 0.24,
        "align": "left",
        "showScrollCue": true,
        "eyebrow": "Dubai Health",
        "heading": "Your family’s care, close to home",
        "body": "We’re a calm, trusted medical partner serving Al Barsha and nearby communities with general practice, pediatrics, dermatology, and reliable lab services."
      },
      {
        "id": "mid",
        "from": 0.34,
        "to": 0.6,
        "align": "right",
        "eyebrow": "What sets us apart",
        "heading": "A human touch with medical precision",
        "body": "We combine compassionate care with reliable diagnostics and convenient hours. Open Saturday through Thursday, 8am-8pm, and we accept most major insurance providers."
      },
      {
        "id": "closing",
        "from": 0.72,
        "to": 1,
        "align": "left",
        "eyebrow": "Ready to connect",
        "heading": "Book a visit with Dubai Health",
        "body": "Start with a quick appointment or ask a question—our team is here to support families in Al Barsha and the surrounding area.",
        "primaryCta": {
          "label": "Book an appointment",
          "href": "#enquiry"
        },
        "secondaryCta": {
          "label": "Explore services",
          "href": "#products"
        }
      }
    ]
  },
  "productsSection": {
    "id": "products",
    "eyebrow": "Our services",
    "heading": "Integrated care for every stage of life",
    "body": "Dubai Health blends routine checkups, diagnostic testing, and targeted therapies into a single, family-friendly clinical experience.",
    "scrollHeightVh": 500,
    "imageAspectRatio": "1:1",
    "items": [
      {
        "category": "Imaging & Diagnostics",
        "name": "Advanced Medical Imaging",
        "description": "High-quality imaging to guide precise diagnoses and treatment decisions across our clinics.",
        "image": "advanced-medical-imaging.jpg"
      },
      {
        "category": "In-House Laboratory",
        "name": "Laboratory Analysis",
        "description": "Fast, reliable lab testing to support timely decisions during visits.",
        "image": "laboratory-analysis.jpg"
      },
      {
        "category": "Orthopedics",
        "name": "Orthopaedic Joint Care",
        "description": "Comprehensive care for joints and musculoskeletal health, helping your family stay active.",
        "image": "orthopaedic-joint-care.jpg"
      },
      {
        "category": "Care & Monitoring",
        "name": "Patient Monitoring",
        "description": "Ongoing follow-up and safety checks to ensure comfort and clarity between appointments.",
        "image": "patient-monitoring.jpg"
      }
    ]
  }
} satisfies SiteConfig;
